#!/bin/sh

# This is wrapper to load agent logs

PATH=/usr/bin
export PATH=$PATH

base=/opt/delta_reporting/

if [[ $1 ]]
then
   cd ${base}/app
   perl -I${base}/perl5/lib/perl5 -Mlocal::lib DeltaR.pl load "$1"
else
   exit 4
fi
