#!/bin/sh 

# This is wrapper to load agent logs

PATH=/usr/bin
export PATH=$PATH

log=$1
base=$(dirname $0)

if [ -e "$log" ]
then
   cd ${base}/..
   perl -I${base}/../../perl5/lib/perl5 -Mlocal::lib DeltaR.pl load "$log"
else
   exit 4
fi
