#!/bin/sh

# Delta Reporting is a central server compliance log that uses CFEngine.
# 
# Copyright (C) 2013 Evolve Thinking http://evolvethinking.com
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Use this to run delta_reporting through morbo during development.

base=$(dirname $0)

if [ $1 ]
then
   listen="-l $1"
fi

cd ${base}/..
env perl -I${base}/../../perl5/lib/perl5 -Mlocal::lib ${base}/../../perl5/bin/morbo ${listen} DeltaR.pl
