#!/bin/sh

# Use this to run delta_reporting through morbo during development.

base=/opt/delta_reporting/

if [ $1 ]
then
   listen="-l $1"
fi

cd ${base}/app
perl -I${base}/perl5/lib/perl5 -Mlocal::lib ${base}/perl5/bin/morbo ${listen} DeltaR.pl
