#!/bin/sh

# This is wrapper to insert summary promise counts

PATH=/usr/bin
export PATH=$PATH

base=$(dirname $0)

cd ${base}/..
perl -I${base}/../../perl5/lib/perl5 -Mlocal::lib DeltaR.pl trends $1
