=head1 Delta Reporting developer testing

=head2 SYNOPSIS

Run all tests with 'DeltaR.pl test'.

=head2 Prerequisites

=over

=item Backup database

Backup any database that your testing may touch, defined in DeltaR.conf.

=item Working database

Some tests insert into, or query the Delta Reporting database. Be sure the
database defined in prerequisites has been created. Test suite will setup and
remove tables automatically.

The tests can be time consuming depending on the power of your database host.

=back

=cut
